In [2]:
# Looding The Library with iris dataset
from sklearn.datasets import load_iris
#loading scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier
# Loading Pandas
import pandas as pd
#loading numpy
import numpy as np
# Setting random seed
np.random.seed(0)

In [9]:
# print(iris)

In [7]:
# Creating an object called iris with the iris data
iris=load_iris()
# Print(iris)
# Creating a dataframe with four features variable
df=pd.DataFrame(iris.data,columns=iris.feature_names)
# Viewing the top 5 rows 
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [11]:
# Adding a new column for the species name
df['species']=pd.Categorical.from_codes(iris.target,iris.target_names)
# viewing the top 5 rows
df.head()
# here we have added the target from iris dataset 
df.tail()
# here we can see dfferent flowers as output so therefore lets see how to train 

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       species  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica

In [12]:
# Creating Test and Train Data
df['is_train']=np.random.uniform(0,1,len(df)) <= 0.75 # the Data is divided into 75% training and 35% test
# Viewing the top 5 rows
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

we can see that is train is showing the boolean value True.

In [13]:
# Creating dataframe with test rows and train rows
train,test = df[df['is_train']==True],df[df['is_train']==False]
# show the number of observations for the test and train dataframes
print('Number of observations in the training data :',len(train))
print('Number of observations in the test data :',len(test))

Number of observations in the training data : 118
Number of observations in the test data : 32


In [14]:
# Create a list of features column's names
features=df.columns[:4]
# View features
print(features)

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')


In [15]:
# Making the species into digital or numeric value so that ML understands
y= pd.factorize(train['species'])[0]
# viewing target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
# Prediction using Random Forest classifier
clf=RandomForestClassifier(n_jobs=2,random_state=0)
# Training the classifier
clf.fit(train[features],y) # fitting or training the data and then prediction sets so it tain the y , y is the target.

RandomForestClassifier(n_jobs=2, random_state=0)

In [17]:
# Applying the trained Classifier to the test 
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
# lets predict the data in another type 
# viewing the predicted probabilities of the first 10 observations
clf.predict_proba(test[features])[0:10]
# here there are 3 flowers in matrix 

array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.95, 0.05, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ]])

In [21]:
# mapping names for the plants for each predictied plant class
preds=iris.target_names[clf.predict(test[features])]
# Viewing the Predicted species for the first five observations 
preds[0:5]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa'], dtype='<U10')

In [23]:
# Viewing the Actual species for the first five observations 
test['species'].head()

7     setosa
8     setosa
10    setosa
13    setosa
17    setosa
Name: species, dtype: category
Categories (3, object): ['setosa', 'versicolor', 'virginica']

In [25]:
# Creating confusion matrix
# Cross tab take 2 sets of data and creates a chart out of them 
pd.crosstab(test['species'],preds,rownames=['Actual Species'],colnames=['predicted Species'])

predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 13           0          0
versicolor              0           5          2
virginica               0           0         12

Here we have 30 accurate values and 2 error so therefore we have almsot 93 % accuracy.

In [28]:
preds=iris.target_names[clf.predict([[5.0,3.6,1.4,2.0],[5.0,3.6,1.4,2.0]])]
preds

/opt/conda/lib/python3.7/site-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array(['setosa', 'setosa'], dtype='<U10')